version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql-data:
    name: mysql-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data

networks:
  mysql-network:
    name: mysql-network
    driver: bridge
